#Arguments
ARG BUILD_FROM=test

FROM $BUILD_FROM

#Start your customizations here

#Example 
#
#PostregSQL and zip suppoer
#RUN set -ex \
#	&& apk --no-cache add postgresql-dev \
#	&& docker-php-ext-install pdo pdo_pgsql zip

#Expose port 80
#EXPOSE 80